# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8e96f3a5b4c081d295b0613bc2e8ccfe3954d9ed66cdf8700043324a8956f88e5d33d0da28dcbd467e2253ded610b95d65943d658a7a17c0ec276b6bd1798c6

test:
  secret_key_base: ba81f76e4a4c53e4b61b5277e4584493ea5de8b7cb8352822f352ae874735083f73fd653148a20bee6e4c04a76226b5bdb437321f0263188835cbecb14c9229f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
